name: publish
on:
  push:
    branches:
      - master

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the ${{ github.repository }} Docker image
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}:latest \
            --push .
